// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgdtodbmrjqjtjziueid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnZHRvZGJtcmpxanRqeml1ZWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNTY0MTIsImV4cCI6MjA2MjkzMjQxMn0.Tp4D8MaeuuGi4ZCJ38EDIS10FVY_Qz4rfla5-jU6120";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);